import "../styles/globals.css";

export const metadata = {
  title: "FrontendBilly",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 1440 320"
          className="fixed border-b-[100px] bottom-0 z-[-999] fill-[#a8f3d0] w-full border-[#a8f3d0] "
        >
          <path d="M0,224L60,208C120,192,240,160,360,160C480,160,600,192,720,192C840,192,960,160,1080,128C1200,96,1320,64,1380,48L1440,32L1440,320L1380,320C1320,320,1200,320,1080,320C960,320,840,320,720,320C600,320,480,320,360,320C240,320,120,320,60,320L0,320Z"></path>
        </svg>
        <ul className="background">
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
        </ul>
      </body>
    </html>
  );
}
