import Head from "next/head";
import Header from "../components/Header";

export default function CaseStudy5() {
  const numbers = [1, 2, 3, 4, 5, 6];
  return (
    <div>
      <Head>
        <title> &#129352; FrontendBilly</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://frontendbilly.netlify.app/img/favicon.png"
        />
        {/* <!-- Global site tag (gtag.js) - Google Analytics --> */}
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-Y7DYRJ7WR1"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-Y7DYRJ7WR1');
  
  `,
          }}
        ></script>
      </Head>
      <div className="font-body">
        <Header />
        <main className="m-auto max-w-2xl mt-36 text-center text-xl flex flex-col gap-6">
          <h1 className="text-2xl">&#129354; WoundApp</h1>
          <p>Code example can be provided on request, due to NDA's</p>
          <div className="mt-6 text-left mb-4 md:mx-0">
            {numbers.map((number) => (
              <img
                src={`/img/woundapp/Frame_${number}.png`}
                alt={number}
                width="800"
                className="m-auto mt-8"
              />
            ))}
          </div>
        </main>
        <section className="text-gray-600 text-left body-font">
          <div className="container px-5 py-24 mx-auto">
            <div className="lg:w-2/3 flex flex-col sm:flex-row sm:items-center items-start mx-auto">
              <h1 className="flex-grow sm:pr-16 text-2xl font-medium title-font text-gray-900">
                If you like what your seeing, drop me a line.
              </h1>
              <a
                className="flex-shrink-0 text-black transition bg-green-300 border-0 py-2 px-8 focus:outline-none hover:bg-green-500 rounded text-lg mt-10 sm:mt-0"
                href="mailto:wilgemcdowell@gmail.com?subject=Lets%20have%20a%20chat"
              >
                Hit me up!
              </a>
            </div>
          </div>
        </section>
        <footer className="text-gray-600 body-font">
          <div className="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
            <a className="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
              <span className="ml-3 text-xl">FrontendBilly</span>
            </a>
            <p className="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">
              © 2021 FrontendBilly
            </p>
            <span className="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
              <a
                className="ml-3 text-gray-500"
                href="https://www.instagram.com/_billymcdowell/"
                target="_blank"
                rel={"noreferrer noopener"}
              >
                <svg
                  fill="none"
                  stroke="currentColor"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  className="w-5 h-5"
                  viewBox="0 0 24 24"
                >
                  <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
                  <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
                </svg>
              </a>
              <a
                className="ml-3 text-gray-500"
                href="https://www.linkedin.com/in/billy-mcdowell-8a4bb4ab/"
                target="_blank"
                rel={"noreferrer noopener"}
              >
                <svg
                  fill="currentColor"
                  stroke="currentColor"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="0"
                  className="w-5 h-5"
                  viewBox="0 0 24 24"
                >
                  <path
                    stroke="none"
                    d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"
                  ></path>
                  <circle cx="4" cy="4" r="2" stroke="none"></circle>
                </svg>
              </a>
            </span>
          </div>
        </footer>
      </div>
    </div>
  );
}
