import Head from "next/head";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Footer from "../components/Footer";
import Work from "../components/Work";
import CTA from "../components/CTA";

export default function Home() {
  return (
    <div>
      <Head>
        <title>FrontendBilly</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://frontendbilly.netlify.app/img/favicon.png"
        />
        {/* <!-- Global site tag (gtag.js) - Google Analytics --> */}
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-Y7DYRJ7WR1"
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `window.dataLayer = window.dataLayer || []; 
                    function gtag(){dataLayer.push(arguments);} 
                    gtag('js', new Date()); 
                    gtag('config', 'G-Y7DYRJ7WR1');`,
          }}
        ></script>
      </Head>
      <div className="font-body">
        <Header />
        <main>
          <Hero />
          <Work />
          <CTA />
        </main>
        <Footer />
      </div>
    </div>
  );
}
