import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>FrontendBilly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg" />
      </Head>
      <body class="font-body">
      <header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <nav class="flex lg:w-2/5 flex-wrap items-center text-base md:ml-auto">
      <a class="border-0 py-1 px-3 focus:outline-none hover:bg-gray-100 transition cursor-pointer rounded text-base mt-4 md:mt-0">About</a>
      <a class="border-0 py-1 px-3 focus:outline-none hover:bg-gray-100 transition cursor-pointer rounded text-base mt-4 md:mt-0">Work</a>
      <a class="border-0 py-1 px-3 focus:outline-none hover:bg-gray-100 transition cursor-pointer rounded text-base mt-4 md:mt-0">Contact</a>
    </nav>
    <a class="flex order-first lg:order-none lg:w-1/5 title-font font-medium items-center text-gray-900 lg:items-center lg:justify-center mb-4 md:mb-0">
      <span class="ml-3 text-xl">FrontendBilly</span>
    </a>
    <div class="lg:w-2/5 inline-flex lg:justify-end ml-5 lg:ml-0">
      <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 transition rounded text-base mt-4 md:mt-0">Check Out CV
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </button>
    </div>
  </div>
</header>
      <main>
      <section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 md:py-24 md:flex-row flex-col items-center">
    <div class="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Before they sold out
        <br class="hidden lg:inline-block"/>readymade gluten
      </h1>
      <p class="mb-8 leading-relaxed">Copper mug try-hard pitchfork pour-over freegan heirloom neutra air plant cold-pressed tacos poke beard tote bag. Heirloom echo park mlkshk tote bag selvage hot chicken authentic tumeric truffaut hexagon try-hard chambray.</p>
      <div class="flex justify-center">
        <button class="inline-flex text-white bg-green-300 border-0 py-2 px-6 focus:outline-none hover:bg-green-500 rounded text-lg transition">Button</button>
        <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg transition">Button</button>
      </div>
    </div>
    <div class="lg:max-w-lg lg:w-full md:w-1/2 xs:w-5/6 order-first md:order-last pb-6">
      <img class="object-cover object-center rounded" alt="hero" src="/img/Headshot.png"/>
    </div>
  </div>
</section>
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="lg:w-2/3 mx-auto">
      <a class="flex flex-wrap w-full bg-gray-100 hover:bg-green-50 transition py-32 px-10 relative mb-4 rounded-lg overflow-hidden cursor-pointer" href="https://acadia-email-sig.netlify.app">
        <img alt="gallery" class="w-full object-cover h-full object-center block opacity-25 absolute inset-0" src="/img/Email-Sig.png"/>
        <div class="text-center relative z-10 w-full">
          <h2 class="text-2xl text-gray-900 font-medium title-font mb-2">Email Sig Generator</h2>
          <p class="leading-relaxed">React, TypeScript, Material-UI, Netlify</p>
          <a class="mt-3 text-grey-600 inline-flex items-center rounded px-2 py-1 bg-green-100">Check it out
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </a>
        </div>
      </a>
      <div class="flex flex-wrap -mx-2">
        <div class="px-2 w-1/2">
          <a class="flex flex-wrap w-full bg-gray-100 hover:bg-green-50 transition sm:py-24 py-16 sm:px-10 px-6 relative rounded-lg overflow-hidden cursor-pointer" href="https://productionriskmanagement.com">
            <img alt="gallery" class="w-full object-cover h-full object-center block opacity-25 absolute inset-0" src="/img/PRM.png"/>
            <div class="text-center relative z-10 w-full">
              <h2 class="text-xl text-gray-900 font-medium title-font mb-2">Production Risk Management</h2>
              <p class="leading-relaxed">Built on Wix</p>
              <a class="mt-3 text-grey-600 inline-flex items-center rounded px-2 py-1 bg-green-100">Check it out
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </a>
        </div>
        <div class="px-2 w-1/2">
          <a class="flex flex-wrap w-full bg-gray-100  hover:bg-green-50 transition sm:py-24 py-16 sm:px-10 px-6 relative rounded-lg overflow-hidden cursor-pointer" href="https://roi-estimator.netlify.app">
            <img alt="gallery" class="w-full object-cover h-full object-center block opacity-25 absolute inset-0" src="/img/ROI.png"/>
            <div class="text-center relative z-10 w-full">
              <h2 class="text-xl text-gray-900 font-medium title-font mb-2">ROI Estimator</h2>
              <p class="leading-relaxed">React, Material-UI, Netlify</p>
              <a class="mt-3 text-grey-600 inline-flex items-center rounded px-2 py-1 bg-green-100">Check it out
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-2/3 flex flex-col sm:flex-row sm:items-center items-start mx-auto">
      <h1 class="flex-grow sm:pr-16 text-2xl font-medium title-font text-gray-900">If you like what your seeing, drop me a line.</h1>
      <button class="flex-shrink-0 text-grey transition bg-green-300 border-0 py-2 px-8 focus:outline-none hover:bg-green-500 rounded text-lg mt-10 sm:mt-0">Hit me up!</button>
    </div>
  </div>
</section>
      </main>

      <footer class="text-gray-600 body-font">
  <div class="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
    <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
      <span class="ml-3 text-xl">FrontendBilly</span>
    </a>
    <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">© 2021 FrontendBilly
    </p>
    <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
      <a class="text-gray-500">
        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-500">
        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-500">
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
          <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-500">
        <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
          <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
          <circle cx="4" cy="4" r="2" stroke="none"></circle>
        </svg>
      </a>
    </span>
  </div>
</footer>
</body>
    </div>
  )
}
