import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>FrontendBilly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://frontendbilly.netlify.app/img/favicon.png" />
        {/* <!-- Global site tag (gtag.js) - Google Analytics --> */}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-Y7DYRJ7WR1"></script>
<script dangerouslySetInnerHTML={{
  __html: `
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-Y7DYRJ7WR1');
  
  `}}>
  
</script>
      </Head>
      <div className="font-body">
      <header className="text-gray-600 body-font">
  <div className="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <nav className="flex lg:w-2/5 flex-wrap items-center text-base md:ml-auto">
      <a className="border-0 py-1 px-3 focus:outline-none hover:bg-gray-100 transition cursor-pointer rounded text-base mt-4 md:mt-0" href="#work">Work</a>
      <a className="border-0 py-1 px-3 focus:outline-none hover:bg-gray-100 transition cursor-pointer rounded text-base mt-4 md:mt-0" href="mailto:wilgemcdowell@gmail.com?subject=Lets%20have%20a%20chat">Contact</a>
    </nav>
    <a className="flex order-first lg:order-none lg:w-1/5 title-font font-medium items-center text-gray-900 lg:items-center lg:justify-center mb-4 md:mb-0">
      <span className="ml-3 text-xl">FrontendBilly</span>
    </a>
    <div className="lg:w-2/5 inline-flex lg:justify-end ml-5 lg:ml-0">
      <a className="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 transition rounded text-base mt-4 md:mt-0" href="/CV/William_McDowell_2021_CV.pdf" rel={"noreferrer noopener"} target="_blank">Check Out CV
        <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" className="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
    </div>
  </div>
</header>
      <main>
      <section className="text-gray-600 body-font">
  <div className="container max-w-7xl w-full mx-auto flex px-5 md:px-12 md:py-24 md:flex-row flex-col items-center">
    <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
      <h1 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Hey I'm Billy,
        <br/>
        
      </h1>
      <h2 className="title-font sm:text-2xl text-xl mb-4 font-small text-gray-900">Experienced UX/UI designer, based in London</h2>
      <p className="mb-8 leading-relaxed">I design complex and data heavy digital experiences for the financial services industry</p>
      <div className="flex justify-center">
        <a className="inline-flex text-black bg-green-300 border-0 py-2 px-6 focus:outline-none hover:bg-green-500 rounded text-lg transition" href="mailto:wilgemcdowell@gmail.com?subject=Lets%20have%20a%20chat">Let's Chat</a>
        <a className="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg transition" href="/CV/William_McDowell_2021_CV.pdf" rel={"noreferrer noopener"} target="_blank">Check out CV</a>
      </div>
    </div>
    <div className="lg:max-w-lg lg:w-full md:w-1/2 xs:w-5/6 order-first md:order-last pb-6">
      <img className="mx-auto" alt="hero" src="/img/Headshot.png"/>
    </div>
  </div>
</section>
 <section className="text-gray-600 body-font" id="work">
 <div className="container px-5 py-12 mx-auto md:items-center">
    <div className="lg:w-2/3 w-full flex flex-col sm:flex-row items-start mx-auto">
    <h2 className="title-font sm:text-2xl sm:text-center text-xl mb-4 font-small text-gray-900">Design &#9997;</h2> </div>
  </div>

  <div className="container px-5 pb-24 mx-auto flex flex-wrap">

    <div className="lg:w-2/3 w-full mx-auto">
      <a className="flex flex-wrap w-full bg-gray-100 hover:bg-green-50 transition py-32 px-10 relative mb-4 rounded-lg overflow-hidden cursor-pointer" href="/CaseStudy1">
        <img alt="gallery" className="w-full object-cover h-full object-center block opacity-25 absolute inset-0" src="/img/Preferences_Profiles.png"/>
        <div className="text-center relative z-10 w-full">
          <h2 className="text-2xl text-gray-900 font-medium title-font mb-2">Preference &amp; Profiles</h2>
          <p className="leading-relaxed">Sketch, Invision Prototype</p>
          <a className="mt-3 text-grey-600 inline-flex items-center rounded px-2 py-1 bg-green-100">Check it out
            <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" className="w-4 h-4 ml-2" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </a>
        </div>
      </a>
      </div>
      <div className="lg:w-2/3 w-full mx-auto">
      <div className="flex flex-wrap -mx-2 pb-4 h-full">
        <div className="px-2 w-1/2">
          <a className="flex flex-wrap w-full bg-gray-100 hover:bg-green-50 transition sm:py-24 py-16 sm:px-10 px-6 relative rounded-lg overflow-hidden cursor-pointer" href="https://productionriskmanagement.com" rel={"noreferrer noopener"} target="_blank">
            <img alt="gallery" className="w-full object-cover h-full object-center block opacity-25 absolute inset-0" src="/img/PRM.png"/>
            <div className="text-center relative z-10 w-full">
              <h2 className="text-xl text-gray-900 font-medium title-font mb-2">Production Risk Management</h2>
              <p className="leading-relaxed">Adobe XD</p>
              <a className="mt-3 text-grey-600 inline-flex items-center rounded px-2 py-1 bg-green-100">Check it out
                <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" className="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </a>
        </div>
        <div className="px-2 w-1/2">
          <a className="flex flex-wrap w-full h-full bg-gray-100 hover:bg-green-50 transition sm:py-24 py-16 sm:px-10 px-6 relative rounded-lg overflow-hidden cursor-pointer" href="/CaseStudy2">
            <img alt="gallery" className="w-full object-cover h-full object-center block opacity-25 absolute inset-0" src="/img/Agreements.png"/>
            <div className="text-center relative z-10 w-full">
              <h2 className="text-xl text-gray-900 font-medium title-font mb-2">Agreements</h2>
              <p className="leading-relaxed">Adobe XD</p>
              <a className="mt-3 text-grey-600 inline-flex items-center rounded px-2 py-1 bg-green-100">Check it out
                <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" className="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </a>
        </div>
        </div>
        </div>
        <div className="lg:w-2/3 w-full mx-auto">
      <a className="flex flex-wrap w-full bg-gray-100 hover:bg-green-50 transition py-32 px-10 relative mb-4 rounded-lg overflow-hidden cursor-pointer" href="https://acadia.inc" rel={"noreferrer noopener"} target="_blank">
        <img alt="gallery" className="w-full object-cover h-full object-center block opacity-25 absolute inset-0" src="/img/Acadia.png"/>
        <div className="text-center relative z-10 w-full">
          <h2 className="text-2xl text-gray-900 font-medium title-font mb-2">Acadia Full Website</h2>
          <p className="leading-relaxed">Design Consultancy</p>
          <a className="mt-3 text-grey-600 inline-flex items-center rounded px-2 py-1 bg-green-100">Check it out
            <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" className="w-4 h-4 ml-2" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </a>
        </div>
      </a>
      </div>
      <div className="lg:w-2/3 w-full mx-auto">
      <div className="flex flex-wrap -mx-2 pb-4 h-full">
        <div className="px-2 w-1/2">
          <a className="flex flex-wrap w-full bg-gray-100 hover:bg-green-50 transition sm:py-24 py-16 sm:px-10 px-6 relative rounded-lg overflow-hidden cursor-pointer" href="/CaseStudy3">
            <img alt="gallery" className="w-full object-cover h-full object-center block opacity-25 absolute inset-0" src="/img/Data_DarkMode.png"/>
            <div className="text-center relative z-10 w-full">
              <h2 className="text-xl text-gray-900 font-medium title-font mb-2">Data Organization</h2>
              <p className="leading-relaxed">Adobe XD</p>
              <a className="mt-3 text-grey-600 inline-flex items-center rounded px-2 py-1 bg-green-100">Check it out
                <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" className="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </a>
        </div>
        <div className="px-2 w-1/2">
          <a className="flex flex-wrap w-full h-full bg-gray-100 hover:bg-green-50 transition sm:py-24 py-16 sm:px-10 px-6 relative rounded-lg overflow-hidden cursor-pointer" href="/CaseStudy4">
            <img alt="gallery" className="w-full object-cover h-full object-center block opacity-25 absolute inset-0" src="/img/Scheduled_Runs.png"/>
            <div className="text-center relative z-10 w-full">
              <h2 className="text-xl text-gray-900 font-medium title-font mb-2">Scheduled Runs</h2>
              <p className="leading-relaxed">Adobe XD</p>
              <a className="mt-3 text-grey-600 inline-flex items-center rounded px-2 py-1 bg-green-100">Check it out
                <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" className="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </a>
        </div>
        </div>
        </div>
      </div>
</section>
<section className="text-gray-600 body-font">
 <div className="container px-5 py-12 mx-auto md:items-center">
    <div className="lg:w-2/3 w-full flex flex-col sm:flex-row items-start mx-auto">
    <h2 className="title-font sm:text-2xl sm:text-center text-xl mb-4 font-small text-gray-900">Code &#128187;</h2> </div>
  </div>

  <div className="container px-5 pb-24 mx-auto flex flex-wrap">

    <div className="lg:w-2/3 w-full mx-auto">
      <a className="flex flex-wrap w-full bg-gray-100 hover:bg-green-50 transition py-32 px-10 relative mb-4 rounded-lg overflow-hidden cursor-pointer" href="https://acadia-email-sig.netlify.app" rel={"noreferrer noopener"} target="_blank">
        <img alt="gallery" className="w-full object-cover h-full object-center block opacity-25 absolute inset-0" src="/img/Email-Sig.png"/>
        <div className="text-center relative z-10 w-full">
          <h2 className="text-2xl text-gray-900 font-medium title-font mb-2">Email Sig Generator</h2>
          <p className="leading-relaxed">React, TypeScript, Material-UI, Netlify</p>
          <a className="mt-3 text-grey-600 inline-flex items-center rounded px-2 py-1 bg-green-100">Check it out
            <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" className="w-4 h-4 ml-2" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </a>
        </div>
      </a>
      </div>
      <div className="lg:w-2/3 w-full mx-auto">
      <div className="flex flex-wrap -mx-2 pb-4 h-full">
        <div className="px-2 w-1/2">
          <a className="flex flex-wrap w-full bg-gray-100 hover:bg-green-50 transition sm:py-24 py-16 sm:px-10 px-6 relative rounded-lg overflow-hidden cursor-pointer" href="https://productionriskmanagement.com" rel={"noreferrer noopener"} target="_blank">
            <img alt="gallery" className="w-full object-cover h-full object-center block opacity-25 absolute inset-0" src="/img/PRM.png"/>
            <div className="text-center relative z-10 w-full">
              <h2 className="text-xl text-gray-900 font-medium title-font mb-2">Production Risk Management</h2>
              <p className="leading-relaxed">Built on Wix</p>
              <a className="mt-3 text-grey-600 inline-flex items-center rounded px-2 py-1 bg-green-100">Check it out
                <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" className="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </a>
        </div>
        <div className="px-2 w-1/2">
          <a className="flex flex-wrap w-full h-full bg-gray-100 hover:bg-green-50 transition sm:py-24 py-16 sm:px-10 px-6 relative rounded-lg overflow-hidden cursor-pointer" href="https://roi-estimator.netlify.app" rel={"noreferrer noopener"} target="_blank">
            <img alt="gallery" className="w-full object-cover h-full object-center block opacity-25 absolute inset-0" src="/img/ROI.png"/>
            <div className="text-center relative z-10 w-full">
              <h2 className="text-xl text-gray-900 font-medium title-font mb-2">ROI Estimator</h2>
              <p className="leading-relaxed">React, Material-UI, Netlify</p>
              <a className="mt-3 text-grey-600 inline-flex items-center rounded px-2 py-1 bg-green-100">Check it out
                <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" className="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </a>
        </div>
        </div>
        </div>
        <div className="lg:w-2/3 w-full mx-auto">
      <a className="flex flex-wrap w-full bg-gray-100 hover:bg-green-50 transition py-32 px-10 relative mb-4 rounded-lg overflow-hidden cursor-pointer" href="https://acadia.inc" target="_blank" rel={"noreferrer noopener"}>
        <img alt="gallery" className="w-full object-cover h-full object-center block opacity-25 absolute inset-0" src="/img/Acadia.png"/>
        <div className="text-center relative z-10 w-full">
          <h2 className="text-2xl text-gray-900 font-medium title-font mb-2">Acadia Full Website</h2>
          <p className="leading-relaxed">Webflow, CMS, Javascript, CSS, HTML</p>
          <a className="mt-3 text-grey-600 inline-flex items-center rounded px-2 py-1 bg-green-100">Check it out
            <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" className="w-4 h-4 ml-2" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </a>
        </div>
      </a>
      </div>
      <div className="lg:w-2/3 w-full mx-auto">
      <div className="flex flex-wrap -mx-2 pb-4 h-full">
        <div className="px-2 w-1/2">
          <a className="flex flex-wrap w-full bg-gray-100 hover:bg-green-50 transition sm:py-24 py-16 sm:px-10 px-6 relative rounded-lg overflow-hidden cursor-pointer" href="https://productionriskmanagement.com" rel={"noreferrer noopener"} target="_blank">
            <img alt="gallery" className="w-full object-cover h-full object-center block opacity-25 absolute inset-0" src="/img/Pause.png"/>
            <div className="text-center relative z-10 w-full">
              <h2 className="text-xl text-gray-900 font-medium title-font mb-2">We are Pause</h2>
              <p className="leading-relaxed">HTML, CSS, JS, Branding, Video Production/Editing</p>
              <a className="mt-3 text-grey-600 inline-flex items-center rounded px-2 py-1 bg-green-100">Check it out
                <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" className="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </a>
        </div>
        <div className="px-2 w-1/2">
          <a className="flex flex-wrap w-full h-full bg-gray-100 hover:bg-green-50 transition sm:py-24 py-16 sm:px-10 px-6 relative rounded-lg overflow-hidden cursor-pointer" href="/">
            <img alt="gallery" className="w-full object-cover h-full object-center block opacity-25 absolute inset-0" src="/img/FrontendBilly.png"/>
            <div className="text-center relative z-10 w-full">
              <h2 className="text-xl text-gray-900 font-medium title-font mb-2">FrontendBilly</h2>
              <p className="leading-relaxed">React, Next.js, Tailwind CSS, Netlify</p>
              <a className="mt-3 text-grey-600 inline-flex items-center rounded px-2 py-1 bg-green-100">Check it out
                <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" className="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </a>
        </div>
        </div>
        </div>
      </div>
</section>
<section className="text-gray-600 body-font">
  <div className="container px-5 py-24 mx-auto">
    <div className="lg:w-2/3 flex flex-col sm:flex-row sm:items-center items-start mx-auto">
      <h1 className="flex-grow sm:pr-16 text-2xl font-medium title-font text-gray-900">If you like what your seeing, drop me a line.</h1>
      <a className="flex-shrink-0 text-black transition bg-green-300 border-0 py-2 px-8 focus:outline-none hover:bg-green-500 rounded text-lg mt-10 sm:mt-0"  href="mailto:wilgemcdowell@gmail.com?subject=Lets%20have%20a%20chat">Hit me up!</a>
    </div>
  </div>
</section>
      </main>

      <footer className="text-gray-600 body-font">
  <div className="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
    <a className="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
      <span className="ml-3 text-xl">FrontendBilly</span>
    </a>
    <p className="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">© 2021 FrontendBilly
    </p>
    <span className="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
      <a className="ml-3 text-gray-500" href="https://www.instagram.com/_billymcdowell/" target="_blank" rel={"noreferrer noopener"}>
        <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" className="w-5 h-5" viewBox="0 0 24 24">
          <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
          <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
        </svg>
      </a>
      <a className="ml-3 text-gray-500" href="https://www.linkedin.com/in/billy-mcdowell-8a4bb4ab/" target="_blank" rel={"noreferrer noopener"}>
        <svg fill="currentColor" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="0" className="w-5 h-5" viewBox="0 0 24 24">
          <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
          <circle cx="4" cy="4" r="2" stroke="none"></circle>
        </svg>
      </a>
    </span>
  </div>
</footer> 
</div>
    </div>
  )
}
